spring:
  cloud:
    stream:
      bindings:
        sendTestData-out-0:
          destination: dataIn
          binder: kafka1
      function:
        definition: sendTestData
      binders:
        kafka1:
          type: kafka
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 9092

